# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/CCDCH/project/project4/Top_test/Top_test.cache/wt [current_project]
set_property parent.project_path D:/CCDCH/project/project4/Top_test/Top_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  d:/CCDCH/project/project4/ip_repo
  d:/CCDCH/project/project4/ip_repo_2
} [current_project]
add_files D:/CCDCH/project/project4/Top_test/Top_test.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all d:/CCDCH/project/project4/Top_test/Top_test.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/CCDCH/project/project4/Top_test/Top_test.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_1/design_1_rst_processing_system7_0_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/CCDCH/project/project4/Top_test/Top_test.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_1/design_1_rst_processing_system7_0_100M_1.xdc]
set_property used_in_implementation false [get_files -all d:/CCDCH/project/project4/Top_test/Top_test.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_1/design_1_rst_processing_system7_0_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CCDCH/project/project4/Top_test/Top_test.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CCDCH/project/project4/Top_test/Top_test.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/CCDCH/project/project4/Top_test/Top_test.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CCDCH/project/project4/Top_test/Top_test.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/CCDCH/project/project4/Top_test/Top_test.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/CCDCH/project/project4/Top_test/Top_test.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files D:/CCDCH/project/project4/Top_test/Top_test.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib D:/CCDCH/project/project4/Top_test/Top_test.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
read_xdc D:/CCDCH/project/project4/Top_test/Top_test.srcs/constrs_1/new/top_cons.xdc
set_property used_in_implementation false [get_files D:/CCDCH/project/project4/Top_test/Top_test.srcs/constrs_1/new/top_cons.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top design_1_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef design_1_wrapper.dcp
catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
